### ISSUE TITLE
[Features] Not support well for nested structure

### ISSUE THREAD

**Issue by rgtjf** [njvack/bids-json-writer#22]
Thanks for this great job!

I tried the cases below, and it missed several important descriptions.

```python
text = """# REPO

intro

## Description

This is an example file

### Application

application

## Authors

* Nate Vack
* Vendor Packages
    * docopt
    * CommonMark-py

## Versions

### Version 1

Here's something about Version 1; I said "Hooray!"

### Version 2

Here's something about Version 2"""

import markdown_to_json
markdown_to_json.dictify(text)
```

Here is the output:
```
OrderedDict([('REPO',
              OrderedDict([('Description',
                            OrderedDict([('Application', 'application')])),
                           ('Authors',
                            ['Nate Vack',
                             'Vendor Packages',
                             ['docopt', 'CommonMark-py']]),
                           ('Versions',
                            OrderedDict([('Version 1',
                                          'Here\'s something about Version 1; I said "Hooray!"'),
                                         ('Version 2',
                                          "Here's something about Version 2")]))]))])
```

the tokens `intro` and `application` are not parsed.

Thanks for your help if you could give some advice!

**Comment by matthewdeanmartin** [comment]
I think those two nodes are not representable. The Commonmark AST is a huge detailed tree of objects and this technique squashes it all down to dictionaries, lists and scalar values- some nodes have nowhere to go. Some obvious stuff gets lost (bold, italic, hyperlinks), but also paragraphs in certain nodes.

Previously the code blew up and displayed nothing. I think what we need is a "strict mode" and possibly warnings when we are allowing a parse to run to completion, but dropping nodes that aren't representable. I'll put it on my TODO list.

If you got better intuition than me, suggest what it should look like & I'll see if it is logically consistent with the rest of the parser.

**Comment by njvack** [comment]
Yeah, I'm not totally sure where that should go; if you have

```
#h1

p1

##h2

p2
```

I guess you _might_ expect:

```
{
  "h1": [
    "p1",
    {
      "h2": "p2"
    }
  ]
}
```

but turning that value into a list would be awfully spooky behavior.

I'd probably either warn about dropped content or simply error on that input. Strict mode is a good idea too.

**Comment by rgtjf** [comment]
how about this format?
```
[{
  "h1": "h1_title",
  "p1": "h1_content",
  "children": [
    {
      "h2": "h2_title",
      "p2": "p2_content:
    }
  ],
}]
```

**Comment by njvack** [comment]
That's not what I'm going for. I'm not saying that it's inherently a _bad_ way to convert markdown to json, just that that's not the approach I want to take.

For the purposes of this library: Content belongs at the leaf nodes. If you mix headings and content at the same level, either dropping content (preferably with a warning) or throwing an error are okay.

**Comment by njvack** [comment]
Also! If you do want to, y'know, just deal with parsed markdown, I would recommend [markdown-it-py](https://github.com/executablebooks/markdown-it-py) — that should give you an AST for any markdown document.

**Comment by matthewdeanmartin** [comment]
All markdown is representable as a full abstract syntax tree. No language has trees as a standard library thing because trees are not general (not like lists & dictionaries), there is no tree that can represent all possible tree types.

Also all markdown is representable as an HTML DOM by converting it HTML and then using any HTML parser and their DOM/AST.

Both markdown-to-json & markpickle (another similar library I'm working on) are lossy representations. For the cost of losing the ability to represent anything you can make with markdown, you get a dead simple representation of the things that can be represented.

(yes I guess you could attempt to put an AST into the built in json serializer and it might work, but it wouldn't be a simple AST, it would be a huge nitpicky AST)

**Comment by njvack** [comment]
FWIW I updated the README to guide people towards markdown-it-py if they want to parse arbitrary markdown, or TOML if they want to do the thing this library was originally designed for

**Comment by rgtjf** [comment]
Thank you for your response! Your replies have effectively addressed my questions!
