### ISSUE TITLE
comment block in markdown

### ISSUE THREAD

**Issue by chrisdecker1201** [njvack/bids-json-writer#25]
Hello,

thank you for this great library :).

I'm wondering if you would like to handle comments in your tool. I've the issue that I'm getting the following markdown file:

```markdown
# latest

<!-- comment -->

* some feature

* bugfix: various bugfixes

# 1.0.0.0

* initiale Version

```

Currently I'm getting the following JSON from your tool:

```json
{
  "latest": "<!-- comment -->\n\n['some feature', 'bugfix: various bugfixes']"
  "1.0.0.0": [
    "initiale Version"
  ]
}
```

I would expect this:

```json
{
  "latest": [
    "some feature",
    "bugfix: various bugfixes"
  ],
  "1.0.0.0": [
    "initiale Version"
  ]
}
```

**Comment by njvack** [comment]
As far as I can tell, Markdown doesn't have a comment syntax. Yes, you can put an HTML comment in there, but I don't really want to get into the "parsing HTML" world.

I would tend to say the library is producing the output I would expect.

**Comment by njvack** [comment]
I guess the thing where Nestle shows up in the output but isn't in the input is a surprise, but I am guessing that's a typo in the issue?

**Comment by chrisdecker1201** [comment]
Okay :).

Yes that was a typo. I fixed it. I switched back to `pypandoc`, but for simple markdown files, your library is really good :)

**Comment by njvack** [comment]
Thanks! I am still amazed people find uses for it, but I'm glad they are!
