### ISSUE TITLE
Wrong link on pypi.org

### ISSUE THREAD

**Issue by m350** [njvack/bids-json-writer#33]
I found that https://github.com/njvack/markdown_to_json set instead of https://github.com/njvack/markdown-to-json
on page https://pypi.org/project/markdown-to-json/

it would be great to change to correct link.
thanks

**Comment by njvack** [comment]
haha I'd have to remember how to deploy this project to pypi then, wouldn't I?

**Comment by njvack** [comment]
okay, I figured it out! Links are fixed. 2.1.2 is uploaded and identical to 2.1.1

Also, thank you for pointing that out!
