### ISSUE TITLE
Can't mix lists and other content

### ISSUE THREAD

**Issue by AnandDev8** [njvack/bids-json-writer#8]
Hi @njvack ,

I have tried your package for converting rasa bot framework .md file to json convertion
.md file is as follows
```
## happy path
* greet
    - utter_greet
* request_restaurant
    - restaurant_form
    - form{"name": "restaurant_form"}
    - form{"name": null}
    - utter_slots_values
* thankyou
    - utter_noworries

## unhappy path
* greet
    - utter_greet
* request_restaurant
    - restaurant_form
    - form{"name": "restaurant_form"}
* chitchat
    - utter_chitchat
    - restaurant_form
    - form{"name": null}
    - utter_slots_values
* thankyou
    - utter_noworries
```
but while converting json i am facing following

**markdown_to_json.markdown_to_json.ContentError: Error at line 3: Can't mix lists and other content**

Any solutions ?

**Comment by Rmsharks4** [comment]
same issue. Not with Rasa doc, but a parsed HTML2Text Document (Markdown Format).

**Comment by dreyTee** [comment]
Same issue while parsing simple markdown (changelog-generator product):
```
## [3.2.0] - 2021-07-22
### HEADER0
- COMMIT1

### HEADER1
- COMMIT2
- COMMIT3

### HEADER2
- COMMIT4
```
